
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '7F2CE3858539211F78D119ED870FAC47'
    
_lr_action_items = {'$end':([1,3,4,5,7,9,11,12,13,14,15,],[-3,0,-6,-8,-1,-4,-3,-7,-6,-2,-5,]),'TIMES':([4,5,12,13,],[10,-8,-7,10,]),'LPAREN':([0,2,6,10,],[2,2,2,2,]),'NUMBER':([0,2,6,10,],[5,5,5,5,]),'RPAREN':([1,4,5,7,8,9,11,12,13,14,15,],[-3,-6,-8,-1,12,-4,-3,-7,-6,-2,-5,]),'PLUS':([1,4,5,9,11,12,13,15,],[6,-6,-8,-4,6,-7,-6,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'t':([4,13,],[9,15,]),'factor':([0,2,6,10,],[4,4,4,13,]),'term':([0,2,6,],[1,1,11,]),'exp':([1,11,],[7,14,]),'expression':([0,2,],[3,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> term exp','expression',2,'p_binary_operators','calc_ply_2CFG.py',43),
  ('exp -> PLUS term exp','exp',3,'p_binary_operators','calc_ply_2CFG.py',44),
  ('exp -> <empty>','exp',0,'p_binary_operators','calc_ply_2CFG.py',45),
  ('term -> factor t','term',2,'p_binary_operators','calc_ply_2CFG.py',46),
  ('t -> TIMES factor t','t',3,'p_binary_operators','calc_ply_2CFG.py',47),
  ('t -> <empty>','t',0,'p_binary_operators','calc_ply_2CFG.py',48),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_parens','calc_ply_2CFG.py',61),
  ('factor -> NUMBER','factor',1,'p_parens','calc_ply_2CFG.py',62),
]
